# Generated by Django 4.0.3 on 2023-06-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='models',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
