# Generated by Django 4.0.3 on 2023-06-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prmapp', '0002_product_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='models',
            new_name='role',
        ),
    ]
