# Generated by Django 4.0.3 on 2023-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prmapp', '0004_rename_role_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
